### ISSUE TITLE
runTestAndWait() often causes 429 Too Many Requests errors

### ISSUE THREAD

**Issue by rejhgadellaabsl** [catchpoint/WebPageTest.api-nodejs#197]
I noticed that `runTestAndWait()` has recently started to throw 429 errors. It seems to be caused by the polling the function performs.

Related: I tried to set a high number for the `pollResults` option (we used the default, which shouldn't cause 429 either imo :)), but it doesn't seem to do anything, the status updates (e.g., `Waiting at the front of the queue...`) are printed at the same-ish interval regardless of what I configure.

```js
wpt.runTestAndWait( url, {
  location: 'gce-europe-west4',
  connectivity: 'Cable',
  runs: 1,
  firstViewOnly: true,
  keepOriginalUserAgent: true,
  pollResults: 30,
  timeout: 120,
  lighthouse: false,
})
```

```
Testing is in progress, please be patient
Waiting at the front of the queue...
Waiting at the front of the queue...
Waiting at the front of the queue...
Waiting at the front of the queue...
Waiting at the front of the queue...
Waiting at the front of the queue...
Waiting at the front of the queue...
Waiting at the front of the queue...
Test Started 5 seconds ago
Test Started 19 seconds ago
Error
    at Object.<anonymous> (/home/ubuntu/git/bsl-sites/bsl-speedtestmonitor/node_modules/webpagetest/lib/helper.js:213:25)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/ubuntu/git/bsl-sites/bsl-speedtestmonitor/node_modules/webpagetest/lib/webpagetest.js:14:12)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10) {
  name: 'WPTAPIError',
  code: 429,
  message: 'Too Many Requests'
}
```

**Comment by AatibMeer** [comment]
Hello there,

This looks more like a support issue. I would suggest logging a ticket with WebPageTest support at support@webpagetest.org. When submitting your ticket, please include the following information:

- IP Address
- User Agent
- Time when the issue occurred
- Endpoint called

Additionally, please confirm if you are passing the key in the headers.

**Comment by rejhgadellaabsl** [comment]
@AatibMeer I missed your reply. I've just reached out to support. Thanks!

**Comment by levipadre** [comment]
Hi @rejhgadellaabsl. Were you able to solve this? I have the same issue.

**Comment by rejhgadellaabsl** [comment]
Yeah, but it looks like I deleted the emails I exchanged with support...

If I remember correctly, `pollResults` is not the correct parameter to tweak this, you have to set `poll` instead (we've set it to `20` and that seems to work fine)

**Comment by levipadre** [comment]
Thank you @rejhgadellaabsl, I will try it. I appreciate your help.
